DROP TABLE USER_GROUP;
DROP TABLE POST_GROUP;
DROP TABLE POST_IMAGES;
DROP TABLE FAVORITES;
DROP TABLE COMMENTS;
DROP TABLE USERS;
DROP TABLE POSTS;
DROP TABLE IMAGES;
DROP TABLE ADS;
DROP TABLE AD_TYPES;
DROP TABLE CATEGORIES;
DROP TABLE GROUPS;

CREATE TABLE IMAGES (
    ID    NUMBER,
    SRC   VARCHAR2(32) NOT NULL,
    LINE  NUMBER,

    CONSTRAINT IMAGES_PK PRIMARY KEY (ID)
);

CREATE TABLE USERS (
    ID            NUMBER,
    LOGIN         VARCHAR2(32) NOT NULL,
    PASSWORD      VARCHAR2(32) NOT NULL,
    USERNAME      VARCHAR2(32) NOT NULL,
    EMAIL         VARCHAR2(32),
    PHONE_NUMBER  NUMBER,
    SIGNED        NUMBER,
    IMAGE         NUMBER NOT NULL,

    CONSTRAINT USERS_PK PRIMARY KEY (ID),
    CONSTRAINT IMAGES_ID_FK FOREIGN KEY (IMAGE) REFERENCES IMAGES (ID)
);

CREATE TABLE AD_TYPES (
    ID           NUMBER,
    TITLE        VARCHAR2(32) NOT NULL,
    COST         NUMBER,
    DESCRIPTION  VARCHAR2(32),

    CONSTRAINT AD_TYPES_PK PRIMARY KEY (ID)
);

CREATE TABLE ADS (
    ID           NUMBER,
    TYPE         NUMBER NOT NULL,
    CONTRACT     VARCHAR2(32) NOT NULL,

    CONSTRAINT ADS_PK PRIMARY KEY (ID),
    CONSTRAINT ADS_TYPE_FK FOREIGN KEY (TYPE) REFERENCES AD_TYPES (ID)
);

CREATE TABLE CATEGORIES (
    ID           NUMBER,
    TITLE        VARCHAR2(32) NOT NULL,
    DESCRIPTION  VARCHAR2(32),

    CONSTRAINT CATEGORIES_PK PRIMARY KEY (ID)
);

CREATE TABLE POSTS (
    ID             NUMBER,
    TITLE          VARCHAR2(256) NOT NULL,
    CONTENT        VARCHAR2(2048) NOT NULL,
    P_DATE         NUMBER NOT NULL,
    MAIN_IMAGE     NUMBER NOT NULL,
    PRIORITY       NUMBER NOT NULL,
    CATEGORY       NUMBER NOT NULL,
    AD             NUMBER NOT NULL,
    SHARES         NUMBER,
    LIKES          NUMBER,

    CONSTRAINT POSTS_PK PRIMARY KEY (ID),
    CONSTRAINT CATEGORIES_ID_FK FOREIGN KEY (CATEGORY) REFERENCES CATEGORIES (ID),
    CONSTRAINT ADS_ID_FK FOREIGN KEY (AD) REFERENCES ADS (ID),
    CONSTRAINT IMAGES_POSTS_ID_FK FOREIGN KEY (MAIN_IMAGE) REFERENCES IMAGES (ID)
);


CREATE TABLE COMMENTS (
    ID           NUMBER,
    C_DATE       NUMBER NOT NULL,
    CONTENT      VARCHAR2(32) NOT NULL,
    LIKES        NUMBER,
    PARENT       NUMBER,
    USER_ID      NUMBER NOT NULL,
    POST_ID      NUMBER NOT NULL,

    CONSTRAINT COMMENTS_PK PRIMARY KEY (ID),
    CONSTRAINT USERS_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT POSTS_ID_FK FOREIGN KEY (POST_ID) REFERENCES POSTS (ID),
    CONSTRAINT PARENT_ID_FK FOREIGN KEY (PARENT) REFERENCES COMMENTS (ID)

);

CREATE TABLE FAVORITES (
    ID        NUMBER,
    USER_ID   NUMBER NOT NULL,
    POST_ID   NUMBER NOT NULL,

    CONSTRAINT FAVORITES_PK PRIMARY KEY (ID),
    CONSTRAINT USERS_FAVORITES_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT POSTS_ID_FAVORITES_FK FOREIGN KEY (POST_iD) REFERENCES POSTS (ID)
);

CREATE TABLE GROUPS (
    ID           NUMBER,
    OWNER_ID     NUMBER NOT NULL,
    TITLE        VARCHAR2(32) NOT NULL,
    DESCRIPTION  VARCHAR2(32) NOT NULL,

    CONSTRAINT GROUPS_PK PRIMARY KEY (ID)
);


CREATE TABLE POST_GROUP (
    ID         NUMBER,
    POST_ID    NUMBER NOT NULL,
    GROUP_ID   NUMBER NOT NULL,
    
    CONSTRAINT POST_GROUP_PK PRIMARY KEY (ID),
    CONSTRAINT POSTS_GROUP_ID_FK FOREIGN KEY (POST_ID) REFERENCES POSTS (ID),
    CONSTRAINT GROUPS_ID_FK FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (ID) 

);

CREATE TABLE POST_IMAGES (
    ID        NUMBER,
    POST_ID   NUMBER NOT NULL,
    IMAGE_ID  NUMBER NOT NULL,

    CONSTRAINT POST_IMAGES_ID PRIMARY KEY (ID),
    CONSTRAINT POSTS_IMAGES_ID_FK FOREIGN KEY (POST_ID) REFERENCES POSTS (ID),
    CONSTRAINT IMAGES_POST_IMAGES_ID_FK FOREIGN KEY (IMAGE_ID) REFERENCES IMAGES (ID)
);

CREATE TABLE USER_GROUP (
    ID         NUMBER,
    USER_ID    NUMBER NOT NULL,
    GROUP_ID   NUMBER NOT NULL,
    MODER      NUMBER,
    ADMIN      NUMBER,

    CONSTRAINT USER_GROUP_PK PRIMARY KEY (ID),
    CONSTRAINT USERS_GROUP_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT USER_GROUPS_ID_FK FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (ID)
);

INSERT INTO AD_TYPES (ID, TITLE, COST, DESCRIPTION) VALUES (0, 'Маленький баннер', 3500, '120 x 70');
INSERT INTO AD_TYPES (ID, TITLE, COST, DESCRIPTION) VALUES (1, 'Стандарт. баннер', 5500, '290 x 130');
INSERT INTO AD_TYPES (ID, TITLE, COST, DESCRIPTION) VALUES (2, 'Видео-интеграция', 10500, 'макс. 15 сек.');
INSERT INTO AD_TYPES (ID, TITLE, COST, DESCRIPTION) VALUES (3, 'Видео-интеграция', 13500, 'макс. 20 сек.');

INSERT INTO CATEGORIES (ID, TITLE) VALUES (0, 'Коронавирус');
INSERT INTO CATEGORIES (ID, TITLE) VALUES (1, 'Политика');
INSERT INTO CATEGORIES (ID, TITLE) VALUES (2, 'Экономика');
INSERT INTO CATEGORIES (ID, TITLE) VALUES (3, 'Спорт');
INSERT INTO CATEGORIES (ID, TITLE) VALUES (4, 'Религия');
INSERT INTO CATEGORIES (ID, TITLE) VALUES (5, 'Туризм');

INSERT INTO ADS (ID, TYPE, CONTRACT) VALUES (0, 0, 'K2020-020139');
INSERT INTO ADS (ID, TYPE, CONTRACT) VALUES (1, 3, 'K2020-020139');

INSERT INTO IMAGES (ID, SRC) VALUES (0, '/img/mifvu13wennm.png');

INSERT INTO POSTS (ID, TITLE, CONTENT, P_DATE, MAIN_IMAGE, PRIORITY, CATEGORY, AD) VALUES (0, 'Парламент Кузбасса провел форум по законодательной стратегии...', '...', 1607790784368, 0, 2, 1, 1);
